theme: jekyll-theme-hacker
title: Random-Crypto
description: Procedurally generated cryptographic CTF challenge benchmark
github:
  is_project_page: true
  repository_url: https://github.com/aielte-research/Random-Crypto
header_links:
  - title: View on GitHub
    url: https://github.com/muzsail/random-crypto
  - title: Paper (arXiv)
    url: https://arxiv.org/abs/2506.02048